modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"
[[mods]]
modId = "afptweaks"
version = "${file.jarVersion}"
displayName = "AFP Tweaks"
description = '''

'''
[[dependencies.afptweaks]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.afptweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.afptweaks]]
modId = "atlaslib"
mandatory = true
versionRange = "[1.1.5,)"
ordering = "NONE"
side = "BOTH"

