modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "pack_tweaks"
version = "${file.jarVersion}"
displayName = "DungeonQuest"
description = '''

'''
[[dependencies.pack_tweaks]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.pack_tweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
[[dependencies.pack_tweaks]]
modId = "followme"
mandatory = true
ordering = "NONE"
side = "BOTH"
[[dependencies.pack_tweaks]]
modId = "quest_mod"
mandatory = true
ordering = "NONE"
side = "BOTH"
